# Generated by Django 5.0.2 on 2024-05-16 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_devicelocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicelocation',
            name='extra',
            field=models.TextField(blank=True, null=True),
        ),
    ]
