# Generated by Django 5.0.2 on 2024-05-16 11:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_devicelocation_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicelocation',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 5, 16, 11, 42, 43, 116595)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devicelocation',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
